### ISSUE TITLE
Associate with gis shapefile

### ISSUE THREAD

**Issue by grwhumphries** [consbio/gis-metadata-parser#1]
Thanks for this awesome library - it's really really great.  I am wondering about how you might use the output from this to import the metadata to an ArcGIS shapefile - particularly those in geodatabases.   

Basically looking for an "import_to_shapefile" function that supports gdb and folder shps

**Comment by dharvey-consbio** [comment]
Providing export to GIS files is outside the scope of this library for a couple of reasons:

1. Importing XML into metadata for FGDB would require an ArcGIS environment (and associated tooling)
2. It has to focus on doing one thing well (metadata), and different data formats are a big can of worms

However, one possible workaround would be to write the metadata to the same path as the shapefile, and name it the same but with an appended `.xml`; for instance, `my_shapefile.shp.xml`.

Thanks for your enthusiasm. I hope that helps.
