### ISSUE TITLE
FrozenOrderedDict is removed from frozendict version 2.0.2

### ISSUE THREAD

**Issue by nikmolnar** [consbio/gis-metadata-parser#8]
The `frozendict` dependency is listed in `setup.py` as `frozendict >= 1.2`. Since 2.0.2 was recently released, it ends up getting installed whenever `gis-metadata-parser` is freshly installed. This breaks the library, because `gis-metadata-parser` tries to import `FrozenOrderedDict` which no longer exists (or not in the same place).

**Comment by nikmolnar** [comment]
I found where this class was dropped from `frozendict`, but am not clear on whether or not it was intentional: https://github.com/Marco-Sulla/python-frozendict/issues/22

**Comment by dharvey-consbio** [comment]
Looks like there is still active conversation on `python-frozendict` around this.

**Comment by nikmolnar** [comment]
Yes, for the moment, I suggest pinning `frozendict` to version `1.2`.

**Comment by dharvey-consbio** [comment]
The `frozendict` dependency is now pinned at `1.2` in `gis-metadata-parser` version `1.2.6`.

**Comment by Marco-Sulla** [comment]
If your package it's for python 3.6+ and you don't use `__reversed__` or `move_to_end`, you can safely `from frozendict import frozendict as FrozenOrderedDict`, since `frozendict` is based on `dict` and `dict` is ordered by default since Python 3.6

**Comment by nikmolnar** [comment]
Thanks for the tip, @Marco-Sulla!
