### ISSUE TITLE
Added to conda-forge

### ISSUE THREAD

**Issue by jlaura** [consbio/gis-metadata-parser#9]
@dharvey-consbio  I just wanted to give you a heads up that I have submitted both this package and parserutils to conda-forge. This gets your packages into that ecosystem as well (not just in the pypi ecosystem). Whenever you peel a new release, conda-forge will see it and automatically get the feedstock (their recipe) updated. Nothing for you to do!

I wanted to give you a heads up in case you also wanted to be a maintainer on your package over on conda-forge. If so, you can open a PR on the [recipe repo](https://github.com/conda-forge/gis-metadata-parser-feedstock) adding yourself [as a recipe maintainer](https://github.com/conda-forge/gis-metadata-parser-feedstock/blob/master/recipe/meta.yaml#L43).

Many thanks for both this library and parserutils! They are amazing and continue to be a joy to work with.

**Comment by dharvey-consbio** [comment]
Hi @jlaura, thanks for your generous compliments! I will consider opening a PR on the recipe repo. I'll be in touch soon.

**Comment by dharvey-consbio** [comment]
Hi @jlaura, I have checked out the `gis-metadata-parser-feedstock` project and created a branch locally with the change to the README you suggested, but I am unable to push the branch in order to create a PR. Can you grant me access to the repository?

**Comment by jlaura** [comment]
Morning @dharvey-consbio, I've got a PR open [here](https://github.com/conda-forge/gis-metadata-parser-feedstock/pull/2) adding you as a maintainer. This should get you access.

**Comment by dharvey-consbio** [comment]
Thanks @jlaura! Looks good to me, except, doesn't the list of maintainers in the README also need to be changed?
